# Generated by Django 4.0.2 on 2022-10-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecomplected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecomplected',
            new_name='datecompleted',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='immportant',
            new_name='important',
        ),
    ]
